{
 "title": "Forensic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Conflict Count",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  diff\nFROM conflict\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wanted",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "options": {
    "content": " **Culprits:** **{{culprits}}**\n\n---\n1st CommitQC: {{commit1}} \n\n2nd CommitQC: {{commit2}}\n\n1st PrepareQC: {{prepare}}\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round, culprits, commit1, commit2, prepare\nFROM culprits\nORDER BY round"
    }
   ]
  },
  {
   "title": "Conflict Results",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT round, node2, node3 from qcs WHERE NOT node2 <=> node3 OR node2 = \" null \" OR node3 = \" null \";\n"
    }
   ]
  },
  {
   "title": "Network Topology",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  normal AS \"time\",\n  normal\nFROM images\nORDER BY normal"
    }
   ]
  },
  {
   "title": "Conflict Alert",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by node2.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1\nFROM node2\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2\nFROM node2\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3\nFROM node2\nORDER BY round"
    }
   ]
  },
  {
   "title": "Node 0",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by node0.",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1\nFROM node0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2\nFROM node0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3\nFROM node2\nORDER BY round"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "marcusolsson-dynamictext-panel",
   "description": "Show the recent logs of nodes.",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 9 },
   "options": { "content": "### {{id}} logs\n{{content}}" },
   "targets": [
    {
     "rawSql": "SELECT\n  id, content\nFROM text\nWHERE id in ('node0', 'node1', 'node2', 'node3')"
    }
   ]
  },
  {
   "title": "Node 3",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by node3.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1\nFROM node3\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2\nFROM node3\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3\nFROM node3\nORDER BY round"
    }
   ]
  },
  {
   "title": "Twin 0",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by twin0.",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1\nFROM twin0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2\nFROM twin0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3\nFROM twin0\nORDER BY round"
    }
   ]
  },
  {
   "title": "Forensic Range",
   "type": "table",
   "gridPos": { "h": 1, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT * from qcs ORDER BY round DESC LIMIT 4;\n"
    }
   ]
  }
 ]
}